# Generated by Django 2.0.5 on 2018-05-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordp',
            old_name='num_p',
            new_name='count',
        ),
        migrations.AddField(
            model_name='recordp',
            name='pattern',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
