# Generated by Django 2.0.5 on 2018-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findp', '0002_auto_20180531_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordp',
            name='limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordp',
            name='site',
            field=models.CharField(choices=[('reddit', 'Reddit')], default='reddit', max_length=200),
        ),
    ]
